version: 2
jobs:
  memo:
    working_directory: ~/soa2019-group5/memo-service
    docker:
      - image: google/cloud-sdk
    environment:
      SBT_VERSION: 1.2.8
    steps:
      - checkout:
          path: ~/soa2019-group5
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Get sbt binary and setup gcloud sdk
          command: |
            apt update && apt install -y curl openjdk-8-jdk unzip
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt git
            apt-get clean && apt-get autoclean
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
          - memo-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - memo-
      - run:
          name: Compile samplescala dist package
          command: cat /dev/null | sbt clean update dist
      - run:
          name: Change aritfact directory and extract zip
          command: ./extract.sh
      - save_cache:
          key: memo-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/kavinvin-211411/memo-service:latest .
            docker push asia.gcr.io/kavinvin-211411/memo-service:latest
  frontend:
    working_directory: ~/soa2019-group5/lectio-pwa
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019-group5
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/kavinvin-211411/lectio-pwa:latest .
            docker push asia.gcr.io/kavinvin-211411/lectio-pwa:latest

workflows:
  version: 2
  deploy:
    jobs:
      - memo:
          filters:
            branches:
              only:
                - ci
      - frontend:
          filters:
            branches:
              only:
                - ci
