version: 2
jobs:
  docker-push:
    working_directory: ~/soa2019-group5/memo-service
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
    steps:
      - run:
          name: Get sbt binary and setup gcloud sdk
          command: |
            echo 'export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"' >> $BASH_ENV
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            apt update && apt install -y curl google-cloud-sdk
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt git
            apt-get clean && apt-get autoclean
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_COMPUTE_ZONE}
            gcloud auth configure-docker
      - checkout:
        - path: ~/soa2019-group5
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
          - memo-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - memo-
      - run:
          name: Compile samplescala dist package
          command: cat /dev/null | sbt clean update dist
      - run:
          name: Change aritfact directory and extract zip
          command: ./extract.sh
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/kavinvin-211411/memo-service:latest .
            docker push asia.gcr.io/kavinvin-211411/memo-service:latest
      - save_cache:
          key: memo-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  deploy:
    jobs:
      - docker_push:
          filters:
            branches:
              only:
                - memo-service